model:
  fuser:
    type: ConvFuser
    in_channels: [80, 256]
    out_channels: 256
  fuser_student:
    type: ConvFuser
    in_channels: [80, 80]
    out_channels: 256
find_unused_parameters: True
optimizer_config:
  cumulative_iters: 3
