voxel_size: [0.075, 0.075, 0.2]
point_cloud_range: [-54.0, -54.0, -5.0, 54.0, 54.0, 3.0]
#voxel_size: [0.1, 0.1, 0.2]
#point_cloud_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
model:
  encoders:
    camera:
      backbone:
        type: ViTAEv2
        RC_tokens_type: ['window', 'window', 'transformer', 'transformer']
        NC_tokens_type: ['window', 'window', 'transformer', 'transformer']
        stages: 4
        embed_dims: [64, 64, 128, 256]
        token_dims: [64, 128, 256, 512]
        downsample_ratios: [4, 2, 2, 2]
        NC_depth: [2, 2, 8, 2]
        NC_heads: [1, 2, 4, 8]
        RC_heads: [1, 1, 2, 4]
        NC_group: [1, 32, 64, 128]
        RC_group: [1, 16, 32, 64]
        window_size: 7
        mlp_ratio: 4
        drop_rate: 0.
        attn_drop_rate: 0.
        drop_path_rate: 0.2
        out_indices: [1, 2, 3]
        use_checkpoint: false
        init_cfg:
          type: Pretrained
          checkpoint: /CV/users/zhaohaimei3/Vitae-Object-Detection/work_dirs/cascade_mask_rcnn_vitaev2_s_mstrain_480-800_giou_4conv1f_adamw_3x_coco_nuimage/epoch_36.pth #/CV/users/zhaohaimei3/Vitae-Object-Detection/work_dirs/cascade_mask_rcnn_vitaev2_s_mstrain_480-800_giou_4conv1f_adamw_3x_nuimage/epoch_36.pth
      neck:
        type: GeneralizedLSSFPN
        in_channels: [128, 256, 512]
        out_channels: 256
        start_level: 0
        num_outs: 3
        norm_cfg:
          type: BN2d
          requires_grad: true
        act_cfg:
          type: ReLU
          inplace: true
        upsample_cfg:
          mode: bilinear
          align_corners: false      
      vtransform:
        in_channels: 256
        out_channels: 80
        feature_size: ${[image_size[0] // 8, image_size[1] // 8]}
        xbound: [-54.0, 54.0, 0.3] #[-51.2, 51.2, 0.4]
        ybound: [-54.0, 54.0, 0.3] #[-51.2, 51.2, 0.4]
        zbound: [-10.0, 10.0, 20.0]
        dbound: [1.0, 60.0, 0.5]
        downsample: 2
    lidar:
      voxelize:
        point_cloud_range: ${point_cloud_range}
        voxel_size: ${voxel_size}
        max_voxels: [ 120000, 160000 ]
      backbone:
        sparse_shape: [ 1440, 1440, 41 ]
  decoder:
    backbone:
      type: GeneralizedResNet
      in_channels: 256
      blocks:
        - [2, 128, 2]
        - [2, 256, 2]
        - [2, 512, 1]
    neck:
      type: LSSFPN
      in_indices: [-1, 0]
      in_channels: [512, 128]
      out_channels: 256
      scale_factor: 2

optimizer:
  paramwise_cfg:
    custom_keys:
      absolute_pos_embed:
        decay_mult: 0
      relative_position_bias_table:
        decay_mult: 0
      encoders.camera.backbone:
        lr_mult: 0.1


lr_config:
  policy: cyclic
  target_ratio: 5.0
  cyclic_times: 1
  step_ratio_up: 0.4

momentum_config:
  policy: cyclic
  cyclic_times: 1
  step_ratio_up: 0.4

data:
  samples_per_gpu: 6
